[CI] Enable Workload tests for PR validation (#7939)
- Extract the existing job to enumerate the test class names to a custom action, so that it can be re-used
- Split the jobs so linux, and windows ones can run independently. And can have separate list of tests.
- Add a new workflow for running Workload tests, with a corresponding new action `enumerate-template-tests`
- Disable tests on windows/CI that need to trust the SSL certificate
- Also, add an artifact with all the test results for `Integration`, and `Template` workflows.

With this PR the `setup` jobs run independently for each OS, thus allowing their test jobs to start running immediately. This helps because Windows job can be a little slower, and doesn't block the Linux test jobs.

Fixes https://github.com/dotnet/aspire/issues/7583 .

* Address review feedback from @ eerhardt

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -8,6 +8,10 @@ on:
       testShortName:
         required: true
         type: string
+      testProjectPath:
+        # relative the repo root
+        required: false
+        type: string
       testSessionTimeoutMs:
         required: false
         type: string
@@ -19,39 +23,67 @@ on:
       extraTestArgs:
         required: false
         type: string
+      os:
+        required: false
+        type: string
+        default: "ubuntu-latest"
 
 jobs:
 
   test:
-    runs-on: ${{ matrix.os }}
-    strategy:
-        matrix:
-          include:
-            - os: ubuntu-latest
-              name: linux
-              dotnet_script: ./dotnet.sh
-              build_script: ./build.sh
-            - os: windows-latest
-              name: windows
-              dotnet_script: .\dotnet.cmd
-              build_script: .\build.cmd
+    runs-on: ${{ inputs.os }}
     timeout-minutes: 60
-    name: ${{ matrix.name }}
+    name: ${{ inputs.os }}
     steps:
+      - name: Validate arguments
+        shell: pwsh
+        run: |
+          if ([string]::IsNullOrEmpty("${{ inputs.testShortName }}")) {
+            Write-Error "Error: testShortName is required."
+            exit 1
+          }
+
+      - name: Setup vars (Linux)
+        if: ${{ inputs.os == 'ubuntu-latest' }}
+        run: |
+          echo "DOTNET_SCRIPT=./dotnet.sh" >> $GITHUB_ENV
+          echo "BUILD_SCRIPT=./build.sh" >> $GITHUB_ENV
+
+      - name: Setup vars (Windows)
+        if: ${{ inputs.os == 'windows-latest' }}
+        run: |
+          echo "DOTNET_SCRIPT=.\dotnet.cmd" >> $env:GITHUB_ENV
+          echo "BUILD_SCRIPT=.\build.cmd" >> $env:GITHUB_ENV
+
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Trust HTTPS development certificate
-        if: matrix.os == 'ubuntu-latest'
-        run: ${{ matrix.dotnet_script }} dev-certs https --trust
+      - name: Trust HTTPS development certificate (Linux)
+        if: inputs.os == 'ubuntu-latest'
+        run: ${{ env.DOTNET_SCRIPT }} dev-certs https --trust
 
       - name: Verify Docker is running
         # nested docker containers not supported on windows
-        if: matrix.os == 'ubuntu-latest'
+        if: inputs.os == 'ubuntu-latest'
         run: docker info
 
+      - name: Build with packages
+        if: ${{ contains(inputs.testProjectPath, 'Aspire.Workload.Tests') }}
+        env:
+          CI: false
+        run: ${{ env.BUILD_SCRIPT }} -restore -build -ci -pack -testnobuild /bl
+
+      - name: Install sdk for workload testing
+        if: ${{ contains(inputs.testProjectPath, 'Aspire.Workload.Tests') }}
+        env:
+          CI: false
+        run: >
+          ${{ env.DOTNET_SCRIPT }} build ${{ github.workspace }}/tests/workloads.proj
+          /p:SkipPackageCheckForWorkloadTesting=true
+          /bl:${{ github.workspace }}/artifacts/log/Debug/InstallSdkForTesting.binlog
+
       - name: Install Azure Functions Core Tools
-        if: matrix.os == 'ubuntu-latest' && (inputs.testShortName == 'Playground' || inputs.testShortName == 'Azure')
+        if: inputs.os == 'ubuntu-latest' && (inputs.testShortName == 'Playground' || inputs.testShortName == 'Azure')
         run: |
           sudo apt-get update
           sudo apt-get install -y azure-functions-core-tools-4
@@ -61,13 +93,15 @@ jobs:
         shell: pwsh
         env:
           CI: false
-        # Convert the shortname of the test to a project path in tests/
         run: |
           $testShortName = "${{ inputs.testShortName }}"
+          $overrideTestProjectPath = "${{ inputs.testProjectPath }}"
           $projectPath1 = "${{ github.workspace }}/tests/$testShortName.Tests/$testShortName.Tests.csproj"
           $projectPath2 = "${{ github.workspace }}/tests/Aspire.$testShortName.Tests/Aspire.$testShortName.Tests.csproj"
 
-          if (Test-Path -Path $projectPath1) {
+          if (-not [string]::IsNullOrEmpty($overrideTestProjectPath)) {
+              $projectPath = "${{ github.workspace }}/$overrideTestProjectPath"
+          } elseif (Test-Path -Path $projectPath1) {
               $projectPath = $projectPath1
           } elseif (Test-Path -Path $projectPath2) {
               $projectPath = $projectPath2
@@ -82,7 +116,7 @@ jobs:
         env:
           CI: false
         run: |
-          ${{ matrix.build_script }} -restore -ci -build -projects ${{ env.TEST_PROJECT_PATH }}
+          ${{ env.BUILD_SCRIPT }} -restore -ci -build -projects ${{ env.TEST_PROJECT_PATH }}
 
       # Workaround for bug in Azure Functions Worker SDK. See https://github.com/Azure/azure-functions-dotnet-worker/issues/2969.
       - name: Rebuild for Azure Functions project
@@ -90,7 +124,7 @@ jobs:
         env:
           CI: false
         run: |
-          ${{ matrix.dotnet_script }} build ${{ github.workspace }}/playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/AzureFunctionsEndToEnd.Functions.csproj /p:SkipUnstableEmulators=true
+          ${{ env.DOTNET_SCRIPT }} build ${{ github.workspace }}/playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/AzureFunctionsEndToEnd.Functions.csproj /p:SkipUnstableEmulators=true
 
       - name: Run tests
         id: run-tests
@@ -98,12 +132,13 @@ jobs:
           CI: false
           DCP_DIAGNOSTICS_LOG_LEVEL: debug
           DCP_DIAGNOSTICS_LOG_FOLDER: ${{ github.workspace }}/testresults/dcp
+          DISABLE_PLAYWRIGHT_TESTS: ${{ inputs.os == 'ubuntu-latest' }}
         run: >
-          ${{ matrix.dotnet_script }} test ${{ env.TEST_PROJECT_PATH }}
+          ${{ env.DOTNET_SCRIPT }} test ${{ env.TEST_PROJECT_PATH }}
           /p:ContinuousIntegrationBuild=true
           -s eng/testing/.runsettings
           -l "console;verbosity=normal"
-          -l "trx"
+          -l "trx;LogFileName=${{ inputs.testShortName }}-TestResults.trx"
           -l "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
           "--blame"
           --blame-hang-timeout ${{ inputs.testHangTimeout }}
@@ -130,7 +165,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: test-job-result-${{ inputs.testShortName }}-${{ matrix.os }}
+          name: test-job-result-${{ inputs.testShortName }}-${{ inputs.os }}
           path: result-*.rst
 
       - name: Dump docker info
@@ -145,7 +180,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: logs-${{ inputs.testShortName }}-${{ matrix.os }}
+          name: logs-${{ inputs.testShortName }}-${{ inputs.os }}
           path: |
             **/*.binlog
             testresults/**
