Extract `enumerate-tests` custom action from `tests.yml`
.. and use independent jobs to get list of tests for Windows, and Linux.

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -19,39 +19,52 @@ on:
       extraTestArgs:
         required: false
         type: string
+      os:
+        required: false
+        type: string
+        default: "ubuntu-latest"
 
 jobs:
 
   test:
-    runs-on: ${{ matrix.os }}
-    strategy:
-        matrix:
-          include:
-            - os: ubuntu-latest
-              name: linux
-              dotnet_script: ./dotnet.sh
-              build_script: ./build.sh
-            - os: windows-latest
-              name: windows
-              dotnet_script: .\dotnet.cmd
-              build_script: .\build.cmd
+    runs-on: ${{ inputs.os }}
     timeout-minutes: 60
-    name: ${{ matrix.name }}
+    name: ${{ inputs.os }}
     steps:
+      - name: Validate arguments
+        shell: pwsh
+        run: |
+          if ([string]::IsNullOrEmpty("${{ inputs.testShortName }}")) {
+            Write-Error "Error: testShortName is required."
+            exit 1
+          }
+
+      - name: Setup vars
+        if: ${{ inputs.os == 'ubuntu-latest' }}
+        run: |
+          echo "dotnet_script=./dotnet.sh" >> $GITHUB_ENV
+          echo "build_script=./build.sh" >> $GITHUB_ENV
+
+      - name: Setup vars
+        if: ${{ inputs.os == 'windows-latest' }}
+        run: |
+          echo "dotnet_script=.\dotnet.cmd" >> $env:GITHUB_ENV
+          echo "build_script=.\build.cmd" >> $env:GITHUB_ENV
+
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Trust HTTPS development certificate
-        if: matrix.os == 'ubuntu-latest'
-        run: ${{ matrix.dotnet_script }} dev-certs https --trust
+      - name: Trust HTTPS development certificate (Linux)
+        if: inputs.os == 'ubuntu-latest'
+        run: ${{ env.dotnet_script }} dev-certs https --trust
 
       - name: Verify Docker is running
         # nested docker containers not supported on windows
-        if: matrix.os == 'ubuntu-latest'
+        if: inputs.os == 'ubuntu-latest'
         run: docker info
 
       - name: Install Azure Functions Core Tools
-        if: matrix.os == 'ubuntu-latest' && (inputs.testShortName == 'Playground' || inputs.testShortName == 'Azure')
+        if: inputs.os == 'ubuntu-latest' && (inputs.testShortName == 'Playground' || inputs.testShortName == 'Azure')
         run: |
           sudo apt-get update
           sudo apt-get install -y azure-functions-core-tools-4
@@ -82,7 +95,7 @@ jobs:
         env:
           CI: false
         run: |
-          ${{ matrix.build_script }} -restore -ci -build -projects ${{ env.TEST_PROJECT_PATH }}
+          ${{ env.build_script }} -restore -ci -build -projects ${{ env.TEST_PROJECT_PATH }}
 
       # Workaround for bug in Azure Functions Worker SDK. See https://github.com/Azure/azure-functions-dotnet-worker/issues/2969.
       - name: Rebuild for Azure Functions project
@@ -90,7 +103,7 @@ jobs:
         env:
           CI: false
         run: |
-          ${{ matrix.dotnet_script }} build ${{ github.workspace }}/playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/AzureFunctionsEndToEnd.Functions.csproj /p:SkipUnstableEmulators=true
+          ${{ env.dotnet_script }} build ${{ github.workspace }}/playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/AzureFunctionsEndToEnd.Functions.csproj /p:SkipUnstableEmulators=true
 
       - name: Run tests
         id: run-tests
@@ -99,7 +112,7 @@ jobs:
           DCP_DIAGNOSTICS_LOG_LEVEL: debug
           DCP_DIAGNOSTICS_LOG_FOLDER: ${{ github.workspace }}/testresults/dcp
         run: >
-          ${{ matrix.dotnet_script }} test ${{ env.TEST_PROJECT_PATH }}
+          ${{ env.dotnet_script }} test ${{ env.TEST_PROJECT_PATH }}
           /p:ContinuousIntegrationBuild=true
           -s eng/testing/.runsettings
           -l "console;verbosity=normal"
@@ -130,7 +143,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: test-job-result-${{ inputs.testShortName }}-${{ matrix.os }}
+          name: test-job-result-${{ inputs.testShortName }}-${{ inputs.os }}
           path: result-*.rst
 
       - name: Dump docker info
@@ -145,7 +158,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: logs-${{ inputs.testShortName }}-${{ matrix.os }}
+          name: logs-${{ inputs.testShortName }}-${{ inputs.os }}
           path: |
             **/*.binlog
             testresults/**
