[CI] Use a simplified condition to check the results of the various jobs instead of using special files

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -222,13 +222,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      # get all the test-job-result* artifacts into a single directory
-      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
-        with:
-          pattern: test-job-result-*
-          merge-multiple: true
-          path: test-job-result
-
       - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
         with:
           pattern: logs-*-ubuntu-latest
@@ -266,7 +259,8 @@ jobs:
           ${{ github.workspace }}/testresults
           --combined
 
-      # return success if zero result-failed-* files are found
-      - name: Compute result
+      - name: Fail if any dependency failed
+        if: ${{ always() && contains(needs.*.result, 'failure') }}" = "true" }}
         run: |
-          [ 0 -eq $(find test-job-result -name 'result-failed-*' | wc -l) ]
+          echo "One or more dependent jobs failed."
+          exit 1
